idf_component_register(
    SRCS
        "recovery_main.cpp"
        "recovery_screen.cpp"
        "recovery_repl.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        esp_system
        esp_timer
        esp_app_format
        log
        freertos
        driver
        esp_lcd
        esp_psram
        st7306_panel
        onebit
        esp_partition
        app_update
        nvs_flash
        console
        espcoredump
        spi_flash
)
