#!/usr/bin/env bash
# flash.sh — one-shot migration flash for the factory+ota layout.
#
# Builds both sibling projects (esp32_recovery + esp32_rendering), then
# writes bootloader + partition-table + factory + ota_0 in a single
# esptool invocation. Per-offset write_flash (no merge_bin + no
# --fill-flash-size) so nvs @ 0x9000 / otadata @ 0x10000 / phy_init @
# 0x12000 are NEVER overwritten — wifi_creds and friends survive.
#
# Usage: ./flash.sh [/dev/cu.usbmodemXXXX]
#
# Dev inner-loop after first migration: idf.py -C esp32_rendering flash
# is fine (only ota_0 changes). This script is for the initial
# re-partition event.

set -euo pipefail

PORT="${1:-/dev/cu.usbmodem4101}"
ROOT="$(cd "$(dirname "$0")" && pwd)"

source "$HOME/.espressif/v5.5.2/esp-idf/export.sh" > /dev/null

echo "--- partition-table drift check ---"
diff \
    <(grep -E "^(nvs|otadata|phy_init)," "$ROOT/esp32_rendering/partitions.csv") \
    <(grep -E "^(nvs|otadata|phy_init)," "$ROOT/esp32_recovery/partitions.csv") \
    || { echo "ERROR: nvs/otadata/phy_init rows differ between projects — fix before flashing"; exit 2; }
echo "ok"

echo "--- build recovery ---"
idf.py -C "$ROOT/esp32_recovery" build

echo "--- build main ---"
idf.py -C "$ROOT/esp32_rendering" build

# Size guard — refuse to flash if recovery outgrew its 512 KB slot.
RECOVERY_SIZE=$(wc -c < "$ROOT/esp32_recovery/build/esp32_recovery.bin")
if [ "$RECOVERY_SIZE" -ge 524288 ]; then
    echo "ERROR: recovery binary is $RECOVERY_SIZE bytes, exceeds 512 KB slot"
    exit 3
fi
echo "recovery size: $RECOVERY_SIZE bytes ($((RECOVERY_SIZE * 100 / 524288))% of slot)"

echo "--- flash (per-offset; nvs/otadata/phy_init untouched) ---"
# Main app builds write esp32_terminal.bin at 0x20000 by default, but the
# new partition table puts ota_0 at 0xA0000. We explicitly place the main
# image at 0xA0000 here — any leftover ota_data_initial.bin generated by
# the main build is ignored (otadata stays whatever's on the chip, which
# is correct: we want the bootloader to find ota_0 and boot it).
python3 -m esptool --chip esp32s3 --port "$PORT" \
    --before default_reset --after hard_reset \
    write_flash \
        0x0       "$ROOT/esp32_recovery/build/bootloader/bootloader.bin" \
        0x8000    "$ROOT/esp32_recovery/build/partition_table/partition-table.bin" \
        0x20000   "$ROOT/esp32_recovery/build/esp32_recovery.bin" \
        0xA0000   "$ROOT/esp32_rendering/build/esp32_terminal.bin"

echo "done. Device should boot main; if it boots recovery instead, run 'reboot-ota' from the recovery REPL."
