// host_test/app/test_ssh_keys_codec.cpp
#include <catch2/catch_test_macros.hpp>
#include <fstream>
#include <sstream>
#include <string>

// key_codec on the host can't fully test without libssh linked in (libssh depends
// on ESP-IDF components). Instead, host test the **format** of the pubkey line
// and **fingerprint derivation** using a reference vector generated by nacl.
//
// A smoke test of the full ssh_pki_export_privkey_to_pubkey path happens
// on-device via the pytest scenario test_ssh_keys_generate.py.

#include "ssh_keys.hpp"

using namespace ssh_keys;

// Pure helper to SHA-256 a blob and produce the OpenSSH SHA256:<b64-no-pad> form.
// Declared in key_codec.hpp; implementation uses mbedtls on-device / OpenSSL on host.
namespace ssh_keys { std::string fingerprint_from_pubkey_blob(const uint8_t* blob, size_t len); }

TEST_CASE("fingerprint format matches OpenSSH ssh-keygen -lf", "[ssh_keys_codec]") {
    // This test doesn't depend on libssh — it only verifies the output format.
    // A realistic OpenSSH blob (51 bytes for ed25519) is fed in; we expect
    // `SHA256:` + 43 b64 chars (no padding).
    //
    // Blob = 4B len(11) + "ssh-ed25519" + 4B len(32) + 32 pubkey bytes.
    uint8_t blob[51] = {
        0x00, 0x00, 0x00, 0x0B,
        's', 's', 'h', '-', 'e', 'd', '2', '5', '5', '1', '9',
        0x00, 0x00, 0x00, 0x20,
        // 32 zero bytes as the pubkey — deterministic
    };
    auto fp = fingerprint_from_pubkey_blob(blob, sizeof(blob));
    REQUIRE(fp.size() == 7 + 43);
    REQUIRE(fp.substr(0, 7) == "SHA256:");
    // no base64 padding
    REQUIRE(fp.find('=') == std::string::npos);
}
